### ISSUE TITLE
pmid2doi of 1000 pmids takes infinite time

### ISSUE THREAD

**Issue by charlesxu90** [metapub/metapub#37]
Dear developers,

I'm trying to use `pmid2doi` to convert a list of `pmid` to `doi`. But it runs very slowly, almost infinitely. Any solution to this?

The code is shown below:
```python
from metapub.convert import pmid2doi

dois = [pmid2doi(pmid) for pmid in df_papers['pmid']]
```

**Comment by nthmost** [comment]
Haven't been able to reproduce this error for lack of time, so I only have some guesses as to what could be going on:

1. You're not using an NCBI API key.  You really need to register your app with the NCBI and insert one via environment variable (NCBI_API_KEY), otherwise you will be severely rate-limited.  See: https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
2. Some of the PMIDs in your list fail to find DOIs in PubMed (uncommon but unfortunately not rare at all).  metapub has a subroutine to handle this which calls CrossRef using author and title, and then tries to back-ref against PubMed to verify its result.  This is a multi-step / multi-API-call operation which can slow things down a lot particularly if you don't have the NCBI API key.

Sorry for such a late reply.  Please add on more information if you have any.  Thanks!
