### ISSUE TITLE
Code vs Site comparison

### ISSUE THREAD

**Issue by shiv265** [metapub/metapub#39]
I am trying to download pmids for certain keywords but the number of entries for a keyword is different when I search using the code and when I search PubMed Manually

**Comment by shiv265** [comment]
I am trying to download pmids for certain keywords but the number of entries for a keyword is different when I search using the code and when I search PubMed Manually

**Comment by nthmost** [comment]
Can you provide me the keywords you're using so i know exactly what you're looking at?

**Comment by einonm** [comment]
I also have seen inconsistencies in this. [Here is an example, manually this gives 3 publications.](https://pubmed.ncbi.nlm.nih.gov/?term=%28alzheimer%29+AND+%28bisoprolol%29&sort=pubdate)

Searching for this returns nothing with the code:

```
keyword = "(alzheimer) AND (bisoprolol)"
fetch = PubMedFetcher()
pmids = fetch.pmids_for_query(keyword, retmax=50)
```

**Comment by einonm** [comment]
An update - the above query now returns results matching the equivalent manual URL search. A temporaty eutils issue?

**Comment by nthmost** [comment]
@einonm I can only guess that the NCBI API index may lag against what the front-end is accessing.  We'd have to talk to someone at NCBI to see what that's about.  My guess is they have a network of database nodes possibly with a hierarchical pattern that gets pushed to the edges over time.  The website may be able to access the top node while the API branches may get pushed the re-indexing a little later.

Or it could have just been a glitch in that moment.

Closing this for now since I don't think it's an issue with metapub itself.
